### ISSUE TITLE
Should DateTime.now_utc/0 should be DateTime.now_utc!/0

### ISSUE THREAD

**Issue by stevedomin** [lau/calendar#16]
Since `DateTime.now_utc/0` can raise, should it be named `DateTime.now_utc!/0` to follow the Elixir convention? (`DateTime.now!` follows it already)

**Comment by lau** [comment]
Have you gotten an error calling that function?

I have thought about that, but I think it is OK to just have one function that raises (as opposed to two functions, one with ! one without).

Not all functions that raise have a ! Example: http://elixir-lang.org/docs/master/elixir/IO.html#chardata_to_string/1

I'm not sure exactly what the convention is, but it seems that it is for when it is likely that function could raise under normal circumstances. The `now!/1` function will raise if you input an invalid timezone identifier.

But if `now_utc/0` fails, I assume something very serious would be wrong. Like a serious hardware failure.

So I'm not sure if two functions (with ! and without) is necessary in this case. Does that make sense?

**Comment by stevedomin** [comment]
Sorry for the late reply @lau 

I was not advocating for a second function, I was only wondering if the existing one should end with `!` but I think I understand the convention a bit more now, it seems that you only need a version with a `!` if you have a version that doesn't raise as well.

We can close that one.

**Comment by lau** [comment]
I can see what you mean. I also think it is a bit asymmetric, but it seems to be the convention.

**Comment by stevedomin** [comment]
Yes, it's fine I'm all for conventions :)
