### ISSUE TITLE
coming feature: durations - FuzzyDuration

### ISSUE THREAD

**Issue by lau** [lau/calendar#22]
Today you can add and subtract seconds to `DateTime`s and `NaiveDateTime`s. And whole days to `Date`s. This is quite exact and devoid of ambiguity.

Some times people want to add "a year" or "two months" to a date or datetime. And it is not always important that the result is super exact.

For this I am planning to add `FuzzyDuration`. It will be a struct can contain years, months, weeks, days, house, minutes, seconds. This will make it easier to work with longer durations at the expense of some accuracy.

The reason for calling it FuzzyDuration and not just Duration is because "a month" is sometimes 28 days, sometimes 31. A year i sometimes 365 days, sometimes 366. So added to different points in time, the duration might be shorter or longer measured in e.g. seconds.

**Comment by stevedomin** [comment]
Out of curiosity, whic cases do you have in mind where the accuracy of the result is not super important?

**Comment by lau** [comment]
If you for instance want to subtract "3 months" from a date, depending on what month the datetime is in, that might be a different number of days.

Or if you want to add "1 week" to a datetime, maybe there will be a DST gap, but what the important part is getting a valid datetime around the same time next week - not that the amount of seconds are always the same.

**Comment by lau** [comment]
Also for instance if you have 1456947112 seconds and want to know how much that is in years, months etc.

**Comment by stevedomin** [comment]
That makes sense, that would be really useful indeed.

**Comment by leefr** [comment]
+1 on this -- It would a scheduler I am working on MUCH easier. I am essentially going to have to do much of the same computation for it to have the desired semantics.
