### ISSUE TITLE
Microsecond precision is too high on Calendar.DateTime.Parse.unix!

### ISSUE THREAD

**Issue by martinsvalin** [lau/calendar#29]
I found that `Calendar.DateTime.Parse.unix!/1` always sets precision to 6 when given a float.

```
dt = Calendar.DateTime.Parse.unix! 1_000_000_000.123
dt.microsecond #=> {123000, 6}
```

I would have expected precision to either match the float I'm supplying (i.e. `1.1000` has precision 4) or the number of significant digits in the decimal part (i.e. `1.1000` has precision 1). Possibly default to significant digits (seems safer not to assume precision), and accept an option like `precise: true` to keep the full precision (after rounding to nearest millionth).

I can help out with the implementation if you're swamped, but want the change.

PS. Thanks for the great work.

**Comment by lau** [comment]
For floats AFAIK 1.1000 and 1.1 are the same thing. Try typing `1.1000` into iex. Float are flawed anyway. 

For strings e.g. `Calendar.DateTime.Parse.unix!("1000000000.123")` it could be implemented and we could get {123000, 3}. Now with the functionality in Elixir 1.3, maybe `DateTime.from_unix` could be used with passing :microsecond as the second argument. You're very welcome to have a go at it if you want.

**Comment by martinsvalin** [comment]
Right, good point about `1.1` and `1.1000`. So then I'd suggest `{100_000, 1}` there, as we can't tell the difference, and it seems safer not to assume more precision than what's implied by the input. Maybe that makes a stronger argument for an option `:precision`, with values 0..6.

```
assert unix!(1_000_000_000).microsecond == {0, 0}
assert unix!(1_000_000_000.000_001).microsecond == {1, 6}
assert unix!(1_000_000_000.1).microsecond == {100_000, 1}
assert unix!(1_000_000_000.123).microsecond == {123_000, 3}
assert unix!(1_000_000_000.100_000).microsecond == {100_000, 1}
assert unix!(1_000_000_000.100_000, precision: 4).microsecond == {100_000, 4}
assert unix!(1_000_000_000.123_456, precision: 1).microsecond == {123_456, 1}
```

For string input, we can use the precision in the string, such that.

```
assert unix!("1000000000.100000").microsecond == {100_000, 6}
assert unix!("1000000000.100000", precision: 4).microsecond == {100_000, 4}
```

Sure, I'll have a go at it.

**Comment by lau** [comment]
We don't need the precision argument option. We can just use the precision in the string.

Unfortunately floats are not precise. So we can default to 6. This is what is done in Elixir 1.3 standard lib when we don't know the precision. E.g. try `NaiveDateTime.new(2000, 1, 1, 0, 0, 0, 100000)`

If you want to know the significant decimals don't use floats. The precision argument in your examples are really manually setting the precision. This can be done in a separate step without having to add additional code. Like this:
`dt |> Map.put(:microsecond, {elem(dt.microsecond, 0), 4})`

You suggestion of using {100_000, 1} for eg. 0.1 is appealing in a way, but it the precision number is misleading. I think {10000, 6} as it is is better. But again floats have issues, so we can't really win with this. Maybe it was not a good idea to support floats in this function at all, but the functionality is already there. Perhaps there should be a warning about floats in the docs that also explains that precision will always be 6.

But the string parsing for sure could be better, currently it doesn't support microseconds.
