### ISSUE TITLE
Feature request: Support "iso8601" as implemented in XML-RPC

### ISSUE THREAD

**Issue by ewildgoose** [lau/calendar#4]
Hi, I'm building an XML-RPC encoder and the spec calls for "iso8601", but it's definition is quite different to ISO's understanding... An example date from the spec is:
    19980717T14:08:55
spec: http://xmlrpc.scripting.com/spec

In particular there is no hyphen between the date elements and no timezone.  

My reading of the ISO spec allows this hyphenless version under some circumstances, and given the spec is implicit using the calendar library I think its defensible to support this?

Lack of timezones is a fairly major departure, and I understand some XML-RPC libraries in the wild will actually supply some timezone here (deviating from the wrong spec towards the correct spec... sigh...).  My thought would be that the timezone should be assumed to be the destination timezone of the parse call?

So, could we please have support for parsing "invalid" rfc3339 dates.  Ideally combinations of both missing hyphens and missing timezones?

**Comment by lau** [comment]
Hi. Adding a parsing function for NaiveDateTime probably makes the most sense in this situation. If there are no timezones specified, it is best to not have the library assume one by default. The parse function could be called NaiveDateTime.Parse.iso8601

I'll look at it soon. Hopefully I can have something implemented within a week.

For datetimes with offsets, simply allowing no separators in the date part should make it work with DateTime.Parse.rfc3339.

**Comment by ewildgoose** [comment]
Thanks for considering this.  

Note, it would be extremely handy to have a parser that I could just throw a this date at and it would "do something sensible".  So the spec says the string should be that hyphenless, tz-less format, BUT, rumour has it that sometimes you will get back hypens and sometimes timezones.  

I see no reason not to be permissive on those two points (more is good, there doesn't seem to be ambiguity either).  However, if I'm going to need to use some regexp and then call an appropriate API function I don't think that flies?  Do you see a way to use Calendar to parse all possible inputs?

Thanks

**Comment by lau** [comment]
I'm doing a NaiveDateTime.Parse.iso8601 function where you could throw all kinds of ISO8601 datetime strings at it. If there is an offset in the string that will be included in the result tuple.

**Comment by lau** [comment]
@ewildgoose I just released version 0.6.8 with ISO8601 parsing. See the docs here: http://hexdocs.pm/calendar/0.6.8/Calendar.NaiveDateTime.Parse.html

This allows you to parse both with and without offset.

**Comment by lau** [comment]
@ewildgoose You can parse them all as a NaiveDateTime. That would be the most sensible thing if you ask me if some of them do not have a timezone offset. Have you tried it? Does it parse the datetimes as you expected?

**Comment by ewildgoose** [comment]
Thanks for this!  I should have reported back before.  I think we should close this for now.  I don't have enough "in the wild" examples to confirm if this covers all cases yet (sorry).  My motivation was in building an XMLRPC lib (see mailing list, it's been announced), where I have to assume that "real world" will throw all kinds of rubbish at me... I guess I'm trying to bring real world problems to your attention. I think this works for me now!  Many thanks!
