### ISSUE TITLE
%Calendar.AmbiguousDateTime{possible_date_times

### ISSUE THREAD

**Issue by ijunaid8989** [lau/calendar#42]
I have been doing date time conversions using `Calendar` everything was working fine for last 4 months but all of sudden am starting some strange behaviour in this, 
what am doing is 

    1..total_days |> Enum.reduce(start_date, fn _i, acc ->
      day_of_week = acc |> Calendar.Date.day_of_week_name
      rec_head = get_head_tail(schedule[day_of_week])
      rec_head |> Enum.each(fn(x) ->
        iterate(x, acc, timezone) |> t_download(interval, t_agent)
      end)
      acc |> Calendar.DateTime.to_erl |> IO.inspect |> Calendar.DateTime.from_erl!(timezone, {123456, 6}) |> IO.inspect |> Calendar.DateTime.add!(86400)
    end)

And the 

    acc |> Calendar.DateTime.to_erl |> IO.inspect |> Calendar.DateTime.from_erl!(timezone, {123456, 6}) |> IO.inspect |> Calendar.DateTime.add!(86400)

give output as 

    {{2016, 10, 27}, {1, 0, 0}}
    %Calendar.DateTime{abbr: "IST", day: 27, hour: 1, min: 0, month: 10, sec: 0,
     std_off: 3600, timezone: "Europe/Dublin", usec: {123456, 6}, utc_off: 0,
     year: 2016}
    {{2016, 10, 28}, {1, 0, 0}}
    %Calendar.DateTime{abbr: "IST", day: 28, hour: 1, min: 0, month: 10, sec: 0,
     std_off: 3600, timezone: "Europe/Dublin", usec: {123456, 6}, utc_off: 0,
     year: 2016}
    {{2016, 10, 29}, {1, 0, 0}}
    %Calendar.DateTime{abbr: "IST", day: 29, hour: 1, min: 0, month: 10, sec: 0,
     std_off: 3600, timezone: "Europe/Dublin", usec: {123456, 6}, utc_off: 0,
     year: 2016}
    {{2016, 10, 30}, {1, 0, 0}}

But on the last date and time instead of giving me right output as it is giving above, It is giving this 

     {:ambiguous, %Calendar.AmbiguousDateTime{possible_date_times: [%Calendar.DateTime{abbr: "GMT", day: 30, hour: 1, min: 0, month: 10, sec: 0, std_off: 0, timezone: "Europe/Dublin", usec: {123456, 6}, utc_off: 0, year: 2016}, %Calendar.DateTime{abbr: "IST", day: 30, hour: 1, min: 0, month: 10, sec: 0, std_off: 3600, timezone: "Europe/Dublin", usec: {123456, 6}, utc_off: 0, year: 2016}]}}

Am totally unknown to that reason as It was working fine but all of sudden its giving me these errors. any help?

**Comment by lau** [comment]
Hi. Did you happen to use tzdata 0.5.17 or 0.5.18? There was an issue with the Dublin time zone in those versions - fixed in 0.5.19+

**Comment by ijunaid8989** [comment]
Hi, Actually, I don't really remember now but I had sorted this problem out somehow. :)
