### ISSUE TITLE
A request regarding the README

### ISSUE THREAD

**Issue by bitwalker** [lau/calendar#5]
Hey @lau, I know this is a bit of an odd request, but I was wondering if you would be willing to revise your line about "The only Elixir library with with accurate, up-to-date time zone information.", as it's no longer true (timex now uses your tzdata library for this, just like calendar). It's up to you obviously, but it would be greatly appreciated.

Cheers and thanks for the great work on tzdata!

Paul

**Comment by lau** [comment]
Of course. Done. I'm glad Timex has up to date timezone info now. Cheers - Lau

**Comment by bitwalker** [comment]
Thank you sir!
