### ISSUE TITLE
1.0 release?

### ISSUE THREAD

**Issue by axelson** [lau/calendar#56]
Is there a reason that this library isn't at a 1.0 version? Do you consider the library itself to be stable? Or are there many features that are still planned.

**Comment by lau** [comment]
Hi,

Good question. 1.0 soon is a good idea. It is pretty stable. I don't plan to add features before 1.0.

**Comment by lau** [comment]
@axelson Hi. An update: 0.18.0 is out. After that I plan to soon release 1.0.

**Comment by axelson** [comment]
Great, thanks!
