### ISSUE TITLE
Confusion about the :tzdata application in mix.exs

### ISSUE THREAD

**Issue by alco** [lau/calendar#9]
In the README you're suggesting to add `:tzdata` to the list of applications. Why not add `:calendar`?

Adding `:calendar` obviates the need for the users to know it depends on `:tzdata`. And if you don't add `:calendar` to the list of applications or at least the list of included applications, it will be omitted when building a release of the host project, leading to `undef` errors when trying to run the release.

**Comment by lau** [comment]
You're totally right. I was planning to change that, but had not gotten around to it.

**Comment by lau** [comment]
Done.
